### ISSUE TITLE
GitBook download link failure

### ISSUE THREAD

**Issue by xxKeith20xx** [learnbyexample/Command-line-text-processing#25]
I didn't have a GitBook account and appears I'm unable to make one with the "legacy" version of the site when clicking on this link:

Download ebook for offline reading - [link](https://www.gitbook.com/book/learnbyexample/command-line-text-processing/details)

```
401
Unauthorized
New accounts should be created on the new version of GitBook. Head to https://www.gitbook.com
```

edit: able to download but wasn't able to preview or attempt to login on the legacy URL

**Comment by learnbyexample** [comment]
I think I will change the download link to only the PDF version (https://legacy.gitbook.com/download/pdf/book/learnbyexample/command-line-text-processing) instead of the current link. That'd prevent the confusion you faced.

For preview, you can use the other link mentioned in README: https://learnbyexample.gitbooks.io/command-line-text-processing/content/
