### ISSUE TITLE
could you investigate error 005 processing error? 

### ISSUE THREAD

**Issue by cbasab-suchetana** [learnbyexample/Command-line-text-processing#31]
google told us there is some 'error 005' in epub file .I can't detect this in error.So I could not publish this book in google book.

**Comment by learnbyexample** [comment]
Can you give some more details about the issue? If you talking about the `epub` version obtained from **gitbook**, I no longer have any control over how the book is generated as they have made the legacy version read only.

Also, may I know why you are trying to publish it on google book? The license certainly allows you to do, provided you follow the guidelines like attribution and you are not commercially selling it. I wish to know why you are trying to publish there instead of sharing just the link to https://legacy.gitbook.com/book/learnbyexample/command-line-text-processing/details.

**Comment by learnbyexample** [comment]
Closing as there's no response from OP. Also, all `legacy.gitbook.com` links are now automatically redirected to `gitbook.com`, so there's no longer an option to download ebooks for offline reading.
